CREATE SCHEMA IF NOT EXISTS sense;

CREATE  TABLE sense.alertaconsolidado ( 
	consolidadoid        bigint  NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	umbralid             bigint  NOT NULL  ,
	fechainicio          timestamptz DEFAULT now() NOT NULL  ,
	fechaultimo          timestamptz DEFAULT now() NOT NULL  ,
	fechaultimacorrida   timestamptz DEFAULT now()   ,
	ultimamedicion       decimal  NOT NULL  ,
	contador             integer DEFAULT 1 NOT NULL  ,
	nivelnotificado      integer    ,
	ultimoenvio          timestamptz    ,
	ultimoescalamiento   timestamptz    ,
	nivelescalamiento    integer    ,
	statusid             integer DEFAULT 1 NOT NULL  ,
	usercreatedid        integer  NOT NULL  ,
	datecreated          timestamptz DEFAULT now() NOT NULL  ,
	usermodifiedid       integer  NOT NULL  ,
	datemodified         timestamptz DEFAULT now() NOT NULL  ,
	CONSTRAINT alerta_consolidado_pkey PRIMARY KEY ( consolidadoid )
 );

CREATE  TABLE sense.codigotelefono ( 
	codigotelefonoid     integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	codigotelefono       varchar(8)  NOT NULL  ,
	paistelefono         varchar(50)  NOT NULL  ,
	statusid             integer DEFAULT 1 NOT NULL  ,
	usercreatedid        integer  NOT NULL  ,
	datecreated          timestamptz DEFAULT now() NOT NULL  ,
	usermodifiedid       integer  NOT NULL  ,
	datemodified         timestamptz DEFAULT now() NOT NULL  ,
	CONSTRAINT pk_codigotelefono_0 PRIMARY KEY ( codigotelefonoid ),
	CONSTRAINT unq_codigotelefono_0 UNIQUE ( codigotelefono, paistelefono ) 
 );

ALTER TABLE sense.codigotelefono ADD CONSTRAINT cns_contacto_0 CHECK ( statusid = ANY (ARRAY[0, 1]) );

CREATE  TABLE sense.criticidad ( 
	criticidadid         integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	criticidad           varchar(20)  NOT NULL  ,
	grado                integer  NOT NULL  ,
	frecuencia           integer DEFAULT 1 NOT NULL  ,
	escalamiento         integer DEFAULT 2 NOT NULL  ,
	escalon              integer  NOT NULL  ,
	statusid             integer DEFAULT 1 NOT NULL  ,
	usercreatedid        integer  NOT NULL  ,
	datecreated          timestamptz DEFAULT now() NOT NULL  ,
	usermodifiedid       integer  NOT NULL  ,
	datemodified         timestamptz DEFAULT now() NOT NULL  ,
	CONSTRAINT pk_origin_0 PRIMARY KEY ( criticidadid ),
	CONSTRAINT unq_criticidad UNIQUE ( criticidad ) 
 );

ALTER TABLE sense.criticidad ADD CONSTRAINT cns_criticidad CHECK ( statusid = ANY (ARRAY[0, 1]) );

CREATE  TABLE sense.entidad ( 
	entidadid            integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	entidad              varchar(50)  NOT NULL  ,
	statusid             integer DEFAULT 1 NOT NULL  ,
	usercreatedid        integer  NOT NULL  ,
	datecreated          timestamptz DEFAULT now() NOT NULL  ,
	usermodifiedid       integer  NOT NULL  ,
	datemodified         timestamptz DEFAULT now() NOT NULL  ,
	CONSTRAINT pk_entidad PRIMARY KEY ( entidadid ),
	CONSTRAINT unq_entidad UNIQUE ( entidad ) 
 );

ALTER TABLE sense.entidad ADD CONSTRAINT cns_entidad CHECK ( statusid = ANY (ARRAY[0, 1]) );

CREATE  TABLE sense.metrica ( 
	metricaid            integer  NOT NULL GENERATED  BY DEFAULT AS IDENTITY ,
	metrica              varchar(50)  NOT NULL  ,
	unidad               varchar(10)  NOT NULL  ,
	statusid             integer DEFAULT 1 NOT NULL  ,
	usercreatedid        integer  NOT NULL  ,
	datecreated          timestamptz DEFAULT now() NOT NULL  ,
	usermodifiedid       integer  NOT NULL  ,
	datemodified         timestamptz DEFAULT now() NOT NULL  ,
	CONSTRAINT metrica_pkey PRIMARY KEY ( metricaid ),
	CONSTRAINT unq_metrica UNIQUE ( metrica ) 
 );

ALTER TABLE sense.metrica ADD CONSTRAINT cns_metrica CHECK ( statusid = ANY (ARRAY[0, 1]) );

CREATE  TABLE sense.nodo ( 
	nodoid               bigint  NOT NULL GENERATED  BY DEFAULT AS IDENTITY ,
	nodo                 varchar(100)  NOT NULL  ,
	deveui               varchar(16)  NOT NULL  ,
	appeui               varchar(16)    ,
	appkey               varchar(32)    ,
	atpin                varchar(50)    ,
	statusid             integer DEFAULT 1 NOT NULL  ,
	usercreatedid        integer  NOT NULL  ,
	datecreated          timestamptz DEFAULT now() NOT NULL  ,
	usermodifiedid       integer  NOT NULL  ,
	datemodified         timestamptz DEFAULT now() NOT NULL  ,
	CONSTRAINT nodo_pkey PRIMARY KEY ( nodoid ),
	CONSTRAINT unq_nodo_0 UNIQUE ( nodo ) ,
	CONSTRAINT unq_nodo UNIQUE ( deveui ) 
 );

ALTER TABLE sense.nodo ADD CONSTRAINT cns_nodo CHECK ( statusid = ANY (ARRAY[0, 1]) );

CREATE  TABLE sense.pais ( 
	paisid               integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	pais                 varchar(50)  NOT NULL  ,
	paisabrev            varchar(2)  NOT NULL  ,
	statusid             integer DEFAULT 1 NOT NULL  ,
	usercreatedid        integer  NOT NULL  ,
	datecreated          timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL  ,
	usermodifiedid       integer  NOT NULL  ,
	datemodified         timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL  ,
	CONSTRAINT pk_pais PRIMARY KEY ( paisid ),
	CONSTRAINT unq_pais_0 UNIQUE ( paisabrev ) ,
	CONSTRAINT unq_pais UNIQUE ( pais ) 
 );

ALTER TABLE sense.pais ADD CONSTRAINT cns_pais CHECK ( statusid = ANY (ARRAY[0, 1]) );

CREATE  TABLE sense.perfil ( 
	perfilid             integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	perfil               varchar(50)  NOT NULL  ,
	nivel                integer DEFAULT 0 NOT NULL  ,
	jefeid               integer    ,
	statusid             integer DEFAULT 1 NOT NULL  ,
	usercreatedid        integer  NOT NULL  ,
	datecreated          timestamptz DEFAULT now() NOT NULL  ,
	usermodifiedid       integer  NOT NULL  ,
	datemodified         timestamptz DEFAULT now() NOT NULL  ,
	CONSTRAINT pk_nivel PRIMARY KEY ( perfilid ),
	CONSTRAINT perfil_perfil_key UNIQUE ( perfil ) 
 );

ALTER TABLE sense.perfil ADD CONSTRAINT cns_perfil CHECK ( statusid = ANY (ARRAY[0, 1]) );

ALTER TABLE sense.perfil ADD CONSTRAINT chk_nivel_hierarchy CHECK ( (jefeid IS NULL) OR (nivel > 0) );

CREATE INDEX idx_perfil_jefeid ON sense.perfil  ( jefeid );

CREATE  TABLE sense.sensor_valor ( 
	id_tipo_sensor       integer  NOT NULL  ,
	id_unidad            integer  NOT NULL  ,
	id_device            varchar(20)  NOT NULL  ,
	valor                double precision  NOT NULL  ,
	fecha                timestamptz  NOT NULL  ,
	statusid             integer DEFAULT '-1'::integer NOT NULL  ,
	CONSTRAINT sensor_valor_pkey PRIMARY KEY ( id_tipo_sensor, id_unidad, id_device, fecha )
 );

ALTER TABLE sense.sensor_valor ADD CONSTRAINT chk_sensor_valor_statusid CHECK ( statusid = ANY (ARRAY['-1'::integer, 0, 1]) );

CREATE INDEX idx_sensor_valor_device_fecha ON sense.sensor_valor  ( id_device, fecha );

CREATE  TABLE sense.sensor_valor_error ( 
	sensorvalorerrorid   bigint  NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	error                varchar(200)  NOT NULL  ,
	id_tipo_sensor       integer  NOT NULL  ,
	id_unidad            integer  NOT NULL  ,
	id_device            varchar(20)  NOT NULL  ,
	valor                double precision  NOT NULL  ,
	fecha                timestamptz  NOT NULL  ,
	statusid             integer DEFAULT '-1'::integer NOT NULL  ,
	CONSTRAINT pk_sensor_valor_error PRIMARY KEY ( sensorvalorerrorid )
 );

ALTER TABLE sense.sensor_valor_error ADD CONSTRAINT chk_sensor_valor_error_statusid CHECK ( statusid = ANY (ARRAY['-1'::integer, 0, 1]) );

CREATE  TABLE sense.tipo ( 
	tipoid               integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	entidadid            integer  NOT NULL  ,
	tipo                 varchar(50)  NOT NULL  ,
	statusid             integer DEFAULT 1 NOT NULL  ,
	usercreatedid        integer  NOT NULL  ,
	datecreated          timestamptz DEFAULT now() NOT NULL  ,
	usermodifiedid       integer  NOT NULL  ,
	datemodified         timestamptz DEFAULT now() NOT NULL  ,
	CONSTRAINT pk_tipo PRIMARY KEY ( tipoid ),
	CONSTRAINT unq_tipo_tipo UNIQUE ( tipo ) ,
	CONSTRAINT unq_tipo_por_entidad UNIQUE ( entidadid, tipo ) 
 );

ALTER TABLE sense.tipo ADD CONSTRAINT cns_tipo CHECK ( statusid = ANY (ARRAY[0, 1]) );

CREATE  TABLE sense.usuario ( 
	usuarioid            integer  NOT NULL GENERATED  BY DEFAULT AS IDENTITY ,
	login                varchar(50)  NOT NULL  ,
	lastname             varchar(50)  NOT NULL  ,
	firstname            varchar(50)  NOT NULL  ,
	statusid             integer DEFAULT 1 NOT NULL  ,
	usercreatedid        integer  NOT NULL  ,
	datecreated          timestamptz DEFAULT now() NOT NULL  ,
	usermodifiedid       integer  NOT NULL  ,
	datemodified         timestamptz DEFAULT now() NOT NULL  ,
	CONSTRAINT usuario_pkey PRIMARY KEY ( usuarioid ),
	CONSTRAINT unq_usuario UNIQUE ( login ) 
 );

ALTER TABLE sense.usuario ADD CONSTRAINT cns_usuario CHECK ( statusid = ANY (ARRAY[0, 1]) );

CREATE  TABLE sense.usuarioperfil ( 
	usuarioid            integer  NOT NULL  ,
	perfilid             integer  NOT NULL  ,
	statusid             integer DEFAULT 1 NOT NULL  ,
	usercreatedid        integer  NOT NULL  ,
	datecreated          timestamptz DEFAULT now() NOT NULL  ,
	usermodifiedid       integer  NOT NULL  ,
	datemodified         timestamptz DEFAULT now() NOT NULL  ,
	CONSTRAINT usuarioperfil_pkey PRIMARY KEY ( usuarioid, perfilid )
 );

ALTER TABLE sense.usuarioperfil ADD CONSTRAINT cns_usuarioperfil CHECK ( statusid = ANY (ARRAY[0, 1]) );

CREATE INDEX idx_usuarioperfil_usuario_act ON sense.usuarioperfil  ( usuarioid, perfilid ) WHERE (statusid = 1);

CREATE INDEX idx_usuarioperfil_perfil_act ON sense.usuarioperfil  ( perfilid ) WHERE (statusid = 1);

CREATE INDEX idx_usuarioperfil_pf_stat ON sense.usuarioperfil  ( perfilid, statusid );

CREATE  TABLE sense.contacto ( 
	contactoid           integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	usuarioid            integer  NOT NULL  ,
	codigotelefonoid     integer  NOT NULL  ,
	celular              varchar(12)  NOT NULL  ,
	statusid             integer DEFAULT 1 NOT NULL  ,
	usercreatedid        integer  NOT NULL  ,
	datecreated          timestamptz DEFAULT now() NOT NULL  ,
	usermodifiedid       integer  NOT NULL  ,
	datemodified         timestamptz DEFAULT now() NOT NULL  ,
	CONSTRAINT pk_contacto PRIMARY KEY ( contactoid )
 );

ALTER TABLE sense.contacto ADD CONSTRAINT cns_contacto CHECK ( statusid = ANY (ARRAY[0, 1]) );

CREATE INDEX idx_contacto_usr_stat ON sense.contacto  ( usuarioid, statusid );

CREATE  TABLE sense.correo ( 
	correoid             integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	usuarioid            integer  NOT NULL  ,
	correo               varchar(50)  NOT NULL  ,
	statusid             integer DEFAULT 1 NOT NULL  ,
	usercreatedid        integer  NOT NULL  ,
	datecreated          timestamptz DEFAULT now() NOT NULL  ,
	usermodifiedid       integer  NOT NULL  ,
	datemodified         timestamptz DEFAULT now() NOT NULL  ,
	CONSTRAINT pk_correo PRIMARY KEY ( correoid )
 );

ALTER TABLE sense.correo ADD CONSTRAINT cns_medio CHECK ( statusid = ANY (ARRAY[0, 1]) );

CREATE  TABLE sense.empresa ( 
	empresaid            integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	paisid               integer  NOT NULL  ,
	empresa              varchar(50)  NOT NULL  ,
	empresabrev          varchar(10)  NOT NULL  ,
	statusid             integer DEFAULT 1 NOT NULL  ,
	usercreatedid        integer  NOT NULL  ,
	datecreated          timestamptz DEFAULT now() NOT NULL  ,
	usermodifiedid       integer  NOT NULL  ,
	datemodified         timestamptz DEFAULT now() NOT NULL  ,
	CONSTRAINT pk_empresa PRIMARY KEY ( empresaid ),
	CONSTRAINT unq_empresa UNIQUE ( paisid, empresa ) ,
	CONSTRAINT unq_empresa_0 UNIQUE ( paisid, empresabrev ) 
 );

ALTER TABLE sense.empresa ADD CONSTRAINT cns_empresa CHECK ( statusid = ANY (ARRAY[0, 1]) );

CREATE  TABLE sense.fundo ( 
	fundoid              integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	empresaid            integer  NOT NULL  ,
	fundo                varchar(50)  NOT NULL  ,
	fundoabrev           varchar(10)  NOT NULL  ,
	statusid             integer DEFAULT 1 NOT NULL  ,
	usercreatedid        integer  NOT NULL  ,
	datecreated          timestamptz DEFAULT now() NOT NULL  ,
	usermodifiedid       integer  NOT NULL  ,
	datemodified         timestamptz DEFAULT now() NOT NULL  ,
	CONSTRAINT pk_fundo PRIMARY KEY ( fundoid ),
	CONSTRAINT unq_fundo UNIQUE ( empresaid, fundo ) ,
	CONSTRAINT unq_fundo_0 UNIQUE ( empresaid, fundoabrev ) 
 );

ALTER TABLE sense.fundo ADD CONSTRAINT cns_fundo CHECK ( statusid = ANY (ARRAY[0, 1]) );

CREATE  TABLE sense.mensaje ( 
	mensajeid            bigint  NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	contactoid           integer  NOT NULL  ,
	consolidadoid        bigint  NOT NULL  ,
	mensaje              varchar(600)  NOT NULL  ,
	fecha                timestamptz DEFAULT now() NOT NULL  ,
	statusid             integer DEFAULT '-1'::integer NOT NULL  ,
	usercreatedid        integer  NOT NULL  ,
	datecreated          timestamptz DEFAULT now() NOT NULL  ,
	CONSTRAINT pk_mensaje PRIMARY KEY ( mensajeid )
 );

ALTER TABLE sense.mensaje ADD CONSTRAINT chk_mensaje_statusid CHECK ( statusid = ANY (ARRAY['-1'::integer, 0, 1]) );

CREATE  TABLE sense.sensor ( 
	nodoid               bigint  NOT NULL  ,
	tipoid               integer  NOT NULL  ,
	statusid             integer DEFAULT 1 NOT NULL  ,
	usercreatedid        integer  NOT NULL  ,
	datecreated          timestamptz DEFAULT now() NOT NULL  ,
	usermodifiedid       integer  NOT NULL  ,
	datemodified         timestamptz DEFAULT now() NOT NULL  ,
	CONSTRAINT pk_sensor PRIMARY KEY ( nodoid, tipoid )
 );

ALTER TABLE sense.sensor ADD CONSTRAINT cns_sensor CHECK ( statusid = ANY (ARRAY[0, 1]) );

CREATE  TABLE sense.ubicacion ( 
	ubicacionid          integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	fundoid              integer  NOT NULL  ,
	ubicacion            varchar(50)  NOT NULL  ,
	statusid             integer DEFAULT 1 NOT NULL  ,
	usercreatedid        integer  NOT NULL  ,
	datecreated          timestamptz DEFAULT now() NOT NULL  ,
	usermodifiedid       integer  NOT NULL  ,
	datemodified         timestamptz DEFAULT now() NOT NULL  ,
	CONSTRAINT ubicacion_pkey PRIMARY KEY ( ubicacionid ),
	CONSTRAINT unq_ubicacion UNIQUE ( fundoid, ubicacion ) 
 );

ALTER TABLE sense.ubicacion ADD CONSTRAINT cns_ubicacion CHECK ( statusid = ANY (ARRAY[0, 1]) );

CREATE  TABLE sense.localizacion ( 
	ubicacionid          integer  NOT NULL  ,
	nodoid               bigint  NOT NULL  ,
	entidadid            integer  NOT NULL  ,
	latitud              decimal(10,6)  NOT NULL  ,
	longitud             decimal(10,6)  NOT NULL  ,
	referencia           varchar(100)    ,
	statusid             integer DEFAULT 1 NOT NULL  ,
	usercreatedid        integer  NOT NULL  ,
	datecreated          timestamptz DEFAULT now() NOT NULL  ,
	usermodifiedid       integer  NOT NULL  ,
	datemodified         timestamptz DEFAULT now() NOT NULL  ,
	CONSTRAINT pk_localizacion PRIMARY KEY ( ubicacionid, nodoid )
 );

ALTER TABLE sense.localizacion ADD CONSTRAINT cns_localizacion CHECK ( statusid = ANY (ARRAY[0, 1]) );

CREATE INDEX idx_localizacion_nodoid ON sense.localizacion  ( nodoid );

CREATE UNIQUE INDEX unico_nodo_activo ON sense.localizacion ( nodoid ) WHERE (statusid = 1);

CREATE  TABLE sense.metricasensor ( 
	nodoid               bigint  NOT NULL  ,
	metricaid            integer  NOT NULL  ,
	tipoid               integer  NOT NULL  ,
	statusid             integer DEFAULT 1 NOT NULL  ,
	usercreatedid        integer  NOT NULL  ,
	usermodifiedid       integer  NOT NULL  ,
	datecreated          timestamptz DEFAULT now() NOT NULL  ,
	datemodified         timestamptz DEFAULT now() NOT NULL  ,
	CONSTRAINT pk_metricasensor PRIMARY KEY ( nodoid, metricaid, tipoid )
 );

ALTER TABLE sense.metricasensor ADD CONSTRAINT cns_metricasensor CHECK ( statusid = ANY (ARRAY[0, 1]) );

CREATE  TABLE sense.umbral ( 
	umbralid             bigint  NOT NULL GENERATED  BY DEFAULT AS IDENTITY ,
	ubicacionid          integer  NOT NULL  ,
	nodoid               bigint  NOT NULL  ,
	tipoid               integer  NOT NULL  ,
	metricaid            integer  NOT NULL  ,
	criticidadid         integer  NOT NULL  ,
	umbral               varchar(50)  NOT NULL  ,
	maximo               double precision  NOT NULL  ,
	minimo               double precision  NOT NULL  ,
	statusid             integer DEFAULT 1 NOT NULL  ,
	usercreatedid        integer  NOT NULL  ,
	datecreated          timestamptz DEFAULT now() NOT NULL  ,
	usermodifiedid       integer  NOT NULL  ,
	datemodified         timestamptz DEFAULT now() NOT NULL  ,
	CONSTRAINT pk_umbral PRIMARY KEY ( umbralid )
 );

ALTER TABLE sense.umbral ADD CONSTRAINT cns_umbral CHECK ( statusid = ANY (ARRAY[0, 1]) );

CREATE INDEX idx_umbral_loc ON sense.umbral  ( ubicacionid, nodoid );

CREATE INDEX idx_umbral_metricasensor ON sense.umbral  ( nodoid, metricaid, tipoid );

CREATE INDEX idx_umbral_lookup_robusto ON sense.umbral  ( nodoid, metricaid, tipoid, ubicacionid, statusid ) WHERE ((statusid = 1) AND (minimo IS NOT NULL) AND (maximo IS NOT NULL));

CREATE  TABLE sense.audit_log_umbral ( 
	auditid              bigint  NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	umbralid             bigint  NOT NULL  ,
	old_minimo           double precision    ,
	new_minimo           double precision    ,
	old_maximo           double precision    ,
	new_maximo           double precision    ,
	old_criticidadid     integer    ,
	new_criticidadid     integer    ,
	accion               varchar(10)  NOT NULL  ,
	modified_by          integer  NOT NULL  ,
	modified_at          timestamptz DEFAULT now() NOT NULL  ,
	CONSTRAINT audit_log_umbral_pkey PRIMARY KEY ( auditid )
 );

ALTER TABLE sense.audit_log_umbral ADD CONSTRAINT audit_log_umbral_accion_check CHECK ( accion)::text = ANY ((ARRAY['INSERT'::character varying, 'UPDATE'::character varying, 'DELETE'::character varying])::text[] );

CREATE  TABLE sense.medicion ( 
	medicionid           bigint  NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	ubicacionid          integer  NOT NULL  ,
	nodoid               bigint  NOT NULL  ,
	tipoid               integer  NOT NULL  ,
	metricaid            integer  NOT NULL  ,
	fecha                timestamptz  NOT NULL  ,
	medicion             double precision  NOT NULL  ,
	usercreatedid        integer  NOT NULL  ,
	datecreated          timestamptz DEFAULT now() NOT NULL  ,
	CONSTRAINT pk_medicion PRIMARY KEY ( medicionid ),
	CONSTRAINT unq_medicion UNIQUE ( ubicacionid, nodoid, tipoid, fecha, metricaid ) 
 );

CREATE INDEX idx_medicion_fecha ON sense.medicion  ( fecha );

CREATE INDEX idx_medicion_sensor_metrica_fecha ON sense.medicion  ( nodoid, tipoid, metricaid, fecha );

CREATE INDEX idx_medicion_ubicacion_nodo_fecha ON sense.medicion  ( ubicacionid, nodoid, fecha );

CREATE  TABLE sense.perfilumbral ( 
	perfilid             integer  NOT NULL  ,
	umbralid             bigint  NOT NULL  ,
	statusid             integer DEFAULT 1 NOT NULL  ,
	usercreatedid        integer  NOT NULL  ,
	datecreated          timestamptz DEFAULT now() NOT NULL  ,
	usermodifiedid       integer  NOT NULL  ,
	datemodified         timestamptz DEFAULT now() NOT NULL  ,
	CONSTRAINT pk_perfilumbral PRIMARY KEY ( perfilid, umbralid )
 );

ALTER TABLE sense.perfilumbral ADD CONSTRAINT cns_perfilumbral CHECK ( statusid = ANY (ARRAY[0, 1]) );

CREATE INDEX idx_perfilumbral_umbral_act ON sense.perfilumbral  ( umbralid, perfilid ) WHERE (statusid = 1);

CREATE INDEX idx_perfilumbral_perfil_act ON sense.perfilumbral  ( perfilid ) WHERE (statusid = 1);

CREATE INDEX idx_perfilumbral_lookup_robusto ON sense.perfilumbral  ( umbralid, perfilid, statusid ) WHERE (statusid = 1);

CREATE  TABLE sense.alerta ( 
	alertaid             bigint  NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	medicionid           bigint  NOT NULL  ,
	umbralid             bigint  NOT NULL  ,
	fecha                timestamptz DEFAULT now() NOT NULL  ,
	statusid             integer DEFAULT 1 NOT NULL  ,
	usercreatedid        integer  NOT NULL  ,
	datecreated          timestamptz DEFAULT now() NOT NULL  ,
	CONSTRAINT alerta_pkey PRIMARY KEY ( alertaid )
 );

ALTER TABLE sense.alerta ADD CONSTRAINT chk_alerta_statusid CHECK ( statusid = ANY (ARRAY[0, 1]) );

ALTER TABLE sense.alerta ADD CONSTRAINT fk_alerta_medicion FOREIGN KEY ( medicionid ) REFERENCES sense.medicion( medicionid );

ALTER TABLE sense.alerta ADD CONSTRAINT fk_alerta_umbral FOREIGN KEY ( umbralid ) REFERENCES sense.umbral( umbralid );

ALTER TABLE sense.audit_log_umbral ADD CONSTRAINT fk_audit_log_umbral_umbral FOREIGN KEY ( umbralid ) REFERENCES sense.umbral( umbralid );

ALTER TABLE sense.contacto ADD CONSTRAINT fk_contacto_usuario FOREIGN KEY ( usuarioid ) REFERENCES sense.usuario( usuarioid );

ALTER TABLE sense.contacto ADD CONSTRAINT fk_contacto_codigotelefono FOREIGN KEY ( codigotelefonoid ) REFERENCES sense.codigotelefono( codigotelefonoid );

ALTER TABLE sense.correo ADD CONSTRAINT fk_correo_usuario FOREIGN KEY ( usuarioid ) REFERENCES sense.usuario( usuarioid );

ALTER TABLE sense.empresa ADD CONSTRAINT fk_empresa_pais FOREIGN KEY ( paisid ) REFERENCES sense.pais( paisid );

ALTER TABLE sense.fundo ADD CONSTRAINT fk_fundo_empresa FOREIGN KEY ( empresaid ) REFERENCES sense.empresa( empresaid );

ALTER TABLE sense.localizacion ADD CONSTRAINT fk_localizacion_nodo FOREIGN KEY ( nodoid ) REFERENCES sense.nodo( nodoid );

ALTER TABLE sense.localizacion ADD CONSTRAINT fk_localizacion_ubicacion FOREIGN KEY ( ubicacionid ) REFERENCES sense.ubicacion( ubicacionid );

ALTER TABLE sense.localizacion ADD CONSTRAINT fk_localizacion_entidad FOREIGN KEY ( entidadid ) REFERENCES sense.entidad( entidadid );

ALTER TABLE sense.medicion ADD CONSTRAINT fk_medicion_localizacion FOREIGN KEY ( ubicacionid, nodoid ) REFERENCES sense.localizacion( ubicacionid, nodoid );

ALTER TABLE sense.medicion ADD CONSTRAINT fk_medicion_metricasensor FOREIGN KEY ( nodoid, metricaid, tipoid ) REFERENCES sense.metricasensor( nodoid, metricaid, tipoid );

ALTER TABLE sense.mensaje ADD CONSTRAINT fk_mensaje_contacto FOREIGN KEY ( contactoid ) REFERENCES sense.contacto( contactoid );

ALTER TABLE sense.mensaje ADD CONSTRAINT fk_mensaje_alertaconsolidado FOREIGN KEY ( consolidadoid ) REFERENCES sense.alertaconsolidado( consolidadoid );

ALTER TABLE sense.metricasensor ADD CONSTRAINT fk_metricadispositivo_metrica FOREIGN KEY ( metricaid ) REFERENCES sense.metrica( metricaid );

ALTER TABLE sense.metricasensor ADD CONSTRAINT fk_metricasensor_sensor FOREIGN KEY ( nodoid, tipoid ) REFERENCES sense.sensor( nodoid, tipoid );

ALTER TABLE sense.perfil ADD CONSTRAINT fk_perfil_jefe FOREIGN KEY ( jefeid ) REFERENCES sense.perfil( perfilid );

ALTER TABLE sense.perfilumbral ADD CONSTRAINT fk_perfilumbral_perfil FOREIGN KEY ( perfilid ) REFERENCES sense.perfil( perfilid );

ALTER TABLE sense.perfilumbral ADD CONSTRAINT fk_perfilumbral_umbral FOREIGN KEY ( umbralid ) REFERENCES sense.umbral( umbralid );

ALTER TABLE sense.sensor ADD CONSTRAINT fk_sensor_nodo FOREIGN KEY ( nodoid ) REFERENCES sense.nodo( nodoid );

ALTER TABLE sense.sensor ADD CONSTRAINT fk_sensor_tipo FOREIGN KEY ( tipoid ) REFERENCES sense.tipo( tipoid );

ALTER TABLE sense.tipo ADD CONSTRAINT fk_tipo_entidad FOREIGN KEY ( entidadid ) REFERENCES sense.entidad( entidadid );

ALTER TABLE sense.ubicacion ADD CONSTRAINT fk_ubicacion_fundo FOREIGN KEY ( fundoid ) REFERENCES sense.fundo( fundoid );

ALTER TABLE sense.umbral ADD CONSTRAINT fk_umbral_criticidad FOREIGN KEY ( criticidadid ) REFERENCES sense.criticidad( criticidadid );

ALTER TABLE sense.umbral ADD CONSTRAINT fk_umbral_localizacion FOREIGN KEY ( ubicacionid, nodoid ) REFERENCES sense.localizacion( ubicacionid, nodoid );

ALTER TABLE sense.umbral ADD CONSTRAINT fk_umbral_metricasensor FOREIGN KEY ( nodoid, metricaid, tipoid ) REFERENCES sense.metricasensor( nodoid, metricaid, tipoid );

ALTER TABLE sense.usuarioperfil ADD CONSTRAINT fk_usuarioperfil_usuario FOREIGN KEY ( usuarioid ) REFERENCES sense.usuario( usuarioid );

ALTER TABLE sense.usuarioperfil ADD CONSTRAINT fk_usuarioperfil_perfil FOREIGN KEY ( perfilid ) REFERENCES sense.perfil( perfilid );

