CREATE SCHEMA IF NOT EXISTS thermo;

CREATE  TABLE thermo.alertaconsolidado ( 
	uuid_alertaconsolidado uuid DEFAULT gen_random_uuid() NOT NULL  ,
	umbralid             bigint  NOT NULL  ,
	fechainicio          timestamptz DEFAULT now() NOT NULL  ,
	fechaultimo          timestamptz DEFAULT now() NOT NULL  ,
	fechaultimacorrida   timestamptz    ,
	ultimamedicion       decimal(12,4)  NOT NULL  ,
	contador             integer DEFAULT 1 NOT NULL  ,
	nivelnotificado      integer    ,
	ultimoenvio          timestamptz    ,
	ultimoescalamiento   timestamptz    ,
	nivelescalamiento    integer    ,
	statusid             integer DEFAULT 1 NOT NULL  ,
	usercreatedid        integer  NOT NULL  ,
	datecreated          timestamptz DEFAULT now() NOT NULL  ,
	usermodifiedid       integer  NOT NULL  ,
	datemodified         timestamptz DEFAULT now() NOT NULL  ,
	CONSTRAINT alertaconsolidado_uuid_alertaconsolidado_key UNIQUE ( uuid_alertaconsolidado ) 
 );

ALTER TABLE thermo.alertaconsolidado ADD CONSTRAINT cns_alertaconsolidado_statusid CHECK ( statusid = ANY (ARRAY[0, 1]) );

CREATE  TABLE thermo.codigotelefono ( 
	codigotelefonoid     integer  NOT NULL  ,
	codigotelefono       varchar(8)  NOT NULL  ,
	paistelefono         varchar(50)  NOT NULL  ,
	statusid             integer DEFAULT 1 NOT NULL  ,
	usercreatedid        integer  NOT NULL  ,
	datecreated          timestamptz DEFAULT now() NOT NULL  ,
	usermodifiedid       integer  NOT NULL  ,
	datemodified         timestamptz DEFAULT now() NOT NULL  ,
	CONSTRAINT unq_codigotelefono UNIQUE ( codigotelefono, paistelefono ) ,
	CONSTRAINT unq_codigotelefono_0 UNIQUE ( codigotelefono ) ,
	CONSTRAINT unq_codigotelefono_1 UNIQUE ( paistelefono ) ,
	CONSTRAINT pk_codigotelefono PRIMARY KEY ( codigotelefonoid )
 );

ALTER TABLE thermo.codigotelefono ADD CONSTRAINT cns_contacto_0 CHECK ( statusid = ANY (ARRAY[0, 1]) );

CREATE INDEX idx_codigotelefono_id ON thermo.codigotelefono  ( codigotelefonoid ) WHERE (statusid = 1);

CREATE  TABLE thermo.criticidad ( 
	criticidadid         integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	criticidad           varchar(20)  NOT NULL  ,
	grado                integer  NOT NULL  ,
	frecuencia           integer  NOT NULL  ,
	escalamiento         integer  NOT NULL  ,
	escalon              integer  NOT NULL  ,
	statusid             integer DEFAULT 1 NOT NULL  ,
	usercreatedid        integer  NOT NULL  ,
	datecreated          timestamptz DEFAULT now() NOT NULL  ,
	usermodifiedid       integer  NOT NULL  ,
	datemodified         timestamptz DEFAULT now() NOT NULL  ,
	CONSTRAINT pk_origin_0 PRIMARY KEY ( criticidadid ),
	CONSTRAINT unq_criticidad UNIQUE ( criticidad ) 
 );

ALTER TABLE thermo.criticidad ADD CONSTRAINT cns_criticidad CHECK ( statusid = ANY (ARRAY[0, 1]) );

CREATE  TABLE thermo.entidad ( 
	entidadid            integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	entidad              varchar(50)  NOT NULL  ,
	statusid             integer DEFAULT 1 NOT NULL  ,
	usercreatedid        integer  NOT NULL  ,
	datecreated          timestamptz DEFAULT now() NOT NULL  ,
	usermodifiedid       integer  NOT NULL  ,
	datemodified         timestamptz DEFAULT now() NOT NULL  ,
	CONSTRAINT pk_entidad PRIMARY KEY ( entidadid ),
	CONSTRAINT unq_entidad UNIQUE ( entidad ) 
 );

ALTER TABLE thermo.entidad ADD CONSTRAINT cns_entidad CHECK ( statusid = ANY (ARRAY[0, 1]) );

CREATE  TABLE thermo.mensaje_error ( 
	mensaje_errorid      bigint  NOT NULL GENERATED  ALWAYS AS IDENTITY ,
	uuid_origen          uuid    ,
	tipo_origen          varchar(20)    ,
	detalle              text    ,
	usercreatedid        integer DEFAULT 0   ,
	datecreated          timestamptz DEFAULT now()   ,
	CONSTRAINT mensaje_error_pkey PRIMARY KEY ( mensaje_errorid )
 );

CREATE  TABLE thermo.metrica ( 
	metricaid            integer  NOT NULL GENERATED  BY DEFAULT AS IDENTITY ,
	metrica              varchar(50)  NOT NULL  ,
	unidad               varchar(10)  NOT NULL  ,
	statusid             integer DEFAULT 1 NOT NULL  ,
	usercreatedid        integer  NOT NULL  ,
	datecreated          timestamptz DEFAULT now() NOT NULL  ,
	usermodifiedid       integer  NOT NULL  ,
	datemodified         timestamptz DEFAULT now() NOT NULL  ,
	CONSTRAINT metrica_pkey PRIMARY KEY ( metricaid ),
	CONSTRAINT unq_metrica UNIQUE ( metrica ) 
 );

ALTER TABLE thermo.metrica ADD CONSTRAINT cns_metrica CHECK ( statusid = ANY (ARRAY[0, 1]) );

CREATE  TABLE thermo.pais ( 
	paisid               integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	pais                 varchar(100)  NOT NULL  ,
	paisabrev            varchar(2)  NOT NULL  ,
	statusid             integer DEFAULT 1 NOT NULL  ,
	usercreatedid        integer  NOT NULL  ,
	datecreated          timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL  ,
	usermodifiedid       integer  NOT NULL  ,
	datemodified         timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL  ,
	CONSTRAINT pk_pais PRIMARY KEY ( paisid ),
	CONSTRAINT unq_pais_0 UNIQUE ( paisabrev ) ,
	CONSTRAINT unq_pais UNIQUE ( pais ) 
 );

ALTER TABLE thermo.pais ADD CONSTRAINT cns_pais CHECK ( statusid = ANY (ARRAY[0, 1]) );

CREATE  TABLE thermo.perfil ( 
	perfilid             integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	perfil               varchar(50)  NOT NULL  ,
	nivel                integer  NOT NULL  ,
	jefeid               integer    ,
	statusid             integer DEFAULT 1 NOT NULL  ,
	usercreatedid        integer  NOT NULL  ,
	datecreated          timestamptz DEFAULT now() NOT NULL  ,
	usermodifiedid       integer  NOT NULL  ,
	datemodified         timestamptz DEFAULT now() NOT NULL  ,
	CONSTRAINT pk_nivel PRIMARY KEY ( perfilid ),
	CONSTRAINT perfil_perfil_key UNIQUE ( perfil ) 
 );

ALTER TABLE thermo.perfil ADD CONSTRAINT cns_perfil CHECK ( statusid = ANY (ARRAY[0, 1]) );

ALTER TABLE thermo.perfil ADD CONSTRAINT chk_nivel_hierarchy CHECK ( (jefeid IS NULL) OR (nivel > 0) );

CREATE  TABLE thermo.sensor_valor ( 
	id_fundo             integer  NOT NULL  ,
	id_sensorlocalizacion integer  NOT NULL  ,
	id_metrica           integer  NOT NULL  ,
	valor                double precision  NOT NULL  ,
	fecha                timestamptz  NOT NULL  ,
	statusid             integer DEFAULT '-1'::integer NOT NULL  ,
	CONSTRAINT sensor_valor_pkey PRIMARY KEY ( id_fundo, id_sensorlocalizacion, fecha, id_metrica )
 );

ALTER TABLE thermo.sensor_valor ADD CONSTRAINT cns_sensor_valor_statusid CHECK ( statusid = ANY (ARRAY['-1'::integer, 0, 1]) );

CREATE INDEX idx_sensor_valor_statusid ON thermo.sensor_valor  ( statusid );

CREATE  TABLE thermo.sensor_valor_error ( 
	sensorvalorerrorid   bigint  NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	error                varchar(1500)  NOT NULL  ,
	id_fundo             integer  NOT NULL  ,
	id_sensorlocalizacion integer  NOT NULL  ,
	id_metrica           integer  NOT NULL  ,
	valor                double precision  NOT NULL  ,
	fecha                timestamptz  NOT NULL  ,
	statusid             integer DEFAULT '-1'::integer NOT NULL  ,
	CONSTRAINT pk_sensor_valor_0 PRIMARY KEY ( sensorvalorerrorid )
 );

ALTER TABLE thermo.sensor_valor_error ADD CONSTRAINT cns_sensor_valor_error_statusid CHECK ( statusid = ANY (ARRAY['-1'::integer, 0, 1]) );

CREATE  TABLE thermo.tipo ( 
	tipoid               integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	tipo                 varchar(50)  NOT NULL  ,
	statusid             integer DEFAULT 1 NOT NULL  ,
	usercreatedid        integer  NOT NULL  ,
	datecreated          timestamptz DEFAULT now() NOT NULL  ,
	usermodifiedid       integer  NOT NULL  ,
	datemodified         timestamptz DEFAULT now() NOT NULL  ,
	CONSTRAINT pk_tipo PRIMARY KEY ( tipoid ),
	CONSTRAINT unq_tipo_tipo UNIQUE ( tipo ) 
 );

ALTER TABLE thermo.tipo ADD CONSTRAINT cns_tipo CHECK ( statusid = ANY (ARRAY[0, 1]) );

CREATE  TABLE thermo.usuario ( 
	usuarioid            integer  NOT NULL GENERATED  BY DEFAULT AS IDENTITY ,
	login                varchar(50)  NOT NULL  ,
	lastname             varchar(50)  NOT NULL  ,
	firstname            varchar(50)  NOT NULL  ,
	statusid             integer DEFAULT 1 NOT NULL  ,
	usercreatedid        integer  NOT NULL  ,
	datecreated          timestamptz DEFAULT now() NOT NULL  ,
	usermodifiedid       integer  NOT NULL  ,
	datemodified         timestamptz DEFAULT now() NOT NULL  ,
	CONSTRAINT usuario_pkey PRIMARY KEY ( usuarioid ),
	CONSTRAINT unq_usuario UNIQUE ( login ) 
 );

ALTER TABLE thermo.usuario ADD CONSTRAINT cns_usuario CHECK ( statusid = ANY (ARRAY[0, 1]) );

CREATE  TABLE thermo.usuarioperfil ( 
	usuarioid            integer  NOT NULL  ,
	perfilid             integer  NOT NULL  ,
	statusid             integer DEFAULT 1 NOT NULL  ,
	usercreatedid        integer  NOT NULL  ,
	datecreated          timestamptz DEFAULT now() NOT NULL  ,
	usermodifiedid       integer  NOT NULL  ,
	datemodified         timestamptz DEFAULT now() NOT NULL  ,
	CONSTRAINT usuarioperfil_pkey PRIMARY KEY ( usuarioid, perfilid )
 );

ALTER TABLE thermo.usuarioperfil ADD CONSTRAINT cns_usuarioperfil CHECK ( statusid = ANY (ARRAY[0, 1]) );

CREATE INDEX idx_usuarioperfil_usuario_act ON thermo.usuarioperfil  ( usuarioid, perfilid ) WHERE (statusid = 1);

CREATE INDEX idx_usuarioperfil_perfil_act ON thermo.usuarioperfil  ( perfilid ) WHERE (statusid = 1);

CREATE  TABLE thermo.contacto ( 
	contactoid           integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	usuarioid            integer  NOT NULL  ,
	codigotelefonoid     integer  NOT NULL  ,
	celular              varchar(20)    ,
	statusid             integer DEFAULT 1 NOT NULL  ,
	usercreatedid        integer  NOT NULL  ,
	datecreated          timestamptz DEFAULT now() NOT NULL  ,
	usermodifiedid       integer  NOT NULL  ,
	datemodified         timestamptz DEFAULT now() NOT NULL  ,
	CONSTRAINT pk_contacto PRIMARY KEY ( contactoid ),
	CONSTRAINT unq_contacto UNIQUE ( usuarioid, codigotelefonoid ) 
 );

ALTER TABLE thermo.contacto ADD CONSTRAINT cns_contacto CHECK ( statusid = ANY (ARRAY[0, 1]) );

CREATE INDEX idx_contacto_usuario ON thermo.contacto  ( usuarioid );

CREATE INDEX idx_contacto_0 ON thermo.contacto  ( codigotelefonoid );

CREATE  TABLE thermo.correo ( 
	correoid             integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	usuarioid            integer  NOT NULL  ,
	correo               varchar(50)    ,
	statusid             integer DEFAULT 1 NOT NULL  ,
	usercreatedid        integer  NOT NULL  ,
	datecreated          timestamptz DEFAULT now() NOT NULL  ,
	usermodifiedid       integer  NOT NULL  ,
	datemodified         timestamptz DEFAULT now() NOT NULL  ,
	CONSTRAINT unq_correo UNIQUE ( correo ) 
 );

ALTER TABLE thermo.correo ADD CONSTRAINT cns_correo CHECK ( statusid = ANY (ARRAY[0, 1]) );

CREATE INDEX pk_correo ON thermo.correo  ( correoid );

CREATE INDEX idx_correo ON thermo.correo  ( usuarioid );

CREATE INDEX idx_correo_usuario ON thermo.correo  ( usuarioid ) WHERE (statusid = 1);

CREATE  TABLE thermo.empresa ( 
	empresaid            integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	paisid               integer  NOT NULL  ,
	empresa              varchar(100)  NOT NULL  ,
	empresabrev          varchar(10)  NOT NULL  ,
	statusid             integer DEFAULT 1 NOT NULL  ,
	usercreatedid        integer  NOT NULL  ,
	datecreated          timestamptz DEFAULT now() NOT NULL  ,
	usermodifiedid       integer  NOT NULL  ,
	datemodified         timestamptz DEFAULT now() NOT NULL  ,
	CONSTRAINT pk_empresa PRIMARY KEY ( empresaid ),
	CONSTRAINT unq_empresa UNIQUE ( paisid, empresa ) ,
	CONSTRAINT unq_empresa_0 UNIQUE ( paisid, empresabrev ) 
 );

ALTER TABLE thermo.empresa ADD CONSTRAINT cns_empresa CHECK ( statusid = ANY (ARRAY[0, 1]) );

CREATE  TABLE thermo.fundo ( 
	fundoid              integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	empresaid            integer  NOT NULL  ,
	fundo                varchar(100)  NOT NULL  ,
	fundoabrev           varchar(10)  NOT NULL  ,
	statusid             integer DEFAULT 1 NOT NULL  ,
	usercreatedid        integer  NOT NULL  ,
	datecreated          timestamptz DEFAULT now() NOT NULL  ,
	usermodifiedid       integer  NOT NULL  ,
	datemodified         timestamptz DEFAULT now() NOT NULL  ,
	CONSTRAINT pk_fundo PRIMARY KEY ( fundoid ),
	CONSTRAINT unq_fundo UNIQUE ( empresaid, fundo ) ,
	CONSTRAINT unq_fundo_0 UNIQUE ( empresaid, fundoabrev ) 
 );

ALTER TABLE thermo.fundo ADD CONSTRAINT cns_fundo CHECK ( statusid = ANY (ARRAY[0, 1]) );

CREATE  TABLE thermo.mensaje ( 
	uuid_origen          uuid  NOT NULL  ,
	contactoid           integer  NOT NULL  ,
	tipo_origen          varchar(20)  NOT NULL  ,
	mensaje              varchar(1000)  NOT NULL  ,
	fecha                timestamptz DEFAULT now() NOT NULL  ,
	statusid             integer DEFAULT 1 NOT NULL  ,
	usercreatedid        integer  NOT NULL  ,
	datecreated          timestamptz DEFAULT now() NOT NULL  ,
	CONSTRAINT pk_mensaje PRIMARY KEY ( uuid_origen, contactoid )
 );

ALTER TABLE thermo.mensaje ADD CONSTRAINT mensaje_tipo_origen_check CHECK ( tipo_origen)::text = ANY ((ARRAY['alerta'::character varying, 'alertaconsolidado'::character varying])::text[] );

ALTER TABLE thermo.mensaje ADD CONSTRAINT cns_mensaje_statusid CHECK ( statusid = ANY (ARRAY[0, 1]) );

CREATE INDEX idx_mensaje ON thermo.mensaje  ( contactoid );

CREATE INDEX idx_mensaje_uuid_tipo ON thermo.mensaje  ( uuid_origen, tipo_origen );

CREATE INDEX idx_mensaje_fecha ON thermo.mensaje  ( fecha );

CREATE  TABLE thermo.sensor ( 
	sensorid             integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	sensor               varchar(50)  NOT NULL  ,
	tipoid               integer  NOT NULL  ,
	statusid             integer DEFAULT 1 NOT NULL  ,
	usercreatedid        integer  NOT NULL  ,
	datecreated          timestamptz DEFAULT now() NOT NULL  ,
	usermodifiedid       integer  NOT NULL  ,
	datemodified         timestamptz DEFAULT now() NOT NULL  ,
	CONSTRAINT pk_sensor PRIMARY KEY ( sensorid ),
	CONSTRAINT unq_sensor UNIQUE ( sensor ) 
 );

ALTER TABLE thermo.sensor ADD CONSTRAINT cns_sensor CHECK ( statusid = ANY (ARRAY[0, 1]) );

CREATE  TABLE thermo.ubicacion ( 
	ubicacionid          integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	fundoid              integer  NOT NULL  ,
	ubicacion            varchar(50)  NOT NULL  ,
	statusid             integer DEFAULT 1 NOT NULL  ,
	usercreatedid        integer  NOT NULL  ,
	datecreated          timestamptz DEFAULT now() NOT NULL  ,
	usermodifiedid       integer  NOT NULL  ,
	datemodified         timestamptz DEFAULT now() NOT NULL  ,
	CONSTRAINT ubicacion_pkey PRIMARY KEY ( ubicacionid )
 );

ALTER TABLE thermo.ubicacion ADD CONSTRAINT cns_ubicacion CHECK ( statusid = ANY (ARRAY[0, 1]) );

CREATE UNIQUE INDEX unq_ubicacion ON thermo.ubicacion ( fundoid, ubicacion );

CREATE  TABLE thermo.localizacion ( 
	localizacionid       integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	ubicacionid          integer  NOT NULL  ,
	entidadid            integer  NOT NULL  ,
	localizacion         varchar(50)  NOT NULL  ,
	statusid             integer DEFAULT 1 NOT NULL  ,
	usercreatedid        integer  NOT NULL  ,
	datecreated          timestamptz DEFAULT now() NOT NULL  ,
	usermodifiedid       integer  NOT NULL  ,
	datemodified         timestamptz DEFAULT now() NOT NULL  ,
	CONSTRAINT pk_localizacion PRIMARY KEY ( localizacionid )
 );

ALTER TABLE thermo.localizacion ADD CONSTRAINT cns_localizacion CHECK ( statusid = ANY (ARRAY[0, 1]) );

CREATE INDEX idx_localizacion ON thermo.localizacion  ( ubicacionid, entidadid );

CREATE  TABLE thermo.metricasensor ( 
	sensorid             integer  NOT NULL  ,
	metricaid            integer  NOT NULL  ,
	statusid             integer DEFAULT 1 NOT NULL  ,
	usercreatedid        integer  NOT NULL  ,
	usermodifiedid       integer  NOT NULL  ,
	datecreated          timestamptz DEFAULT now() NOT NULL  ,
	datemodified         timestamptz DEFAULT now() NOT NULL  ,
	CONSTRAINT pk_metricasensor PRIMARY KEY ( sensorid, metricaid )
 );

ALTER TABLE thermo.metricasensor ADD CONSTRAINT cns_metricasensor CHECK ( statusid = ANY (ARRAY[0, 1]) );

CREATE INDEX idx_metricasensor ON thermo.metricasensor  ( metricaid );

CREATE  TABLE thermo.localizacionsensor ( 
	localizacionsensorid integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	localizacionid       integer  NOT NULL  ,
	sensorid             integer  NOT NULL  ,
	metricaid            integer  NOT NULL  ,
	localizacionsensor   varchar(50)  NOT NULL  ,
	statusid             integer DEFAULT 1 NOT NULL  ,
	usercreatedid        integer  NOT NULL  ,
	datecreated          timestamptz DEFAULT now() NOT NULL  ,
	usermodifiedid       integer  NOT NULL  ,
	datemodified         timestamptz DEFAULT now() NOT NULL  ,
	CONSTRAINT pk_localizacionsensor PRIMARY KEY ( localizacionsensorid )
 );

ALTER TABLE thermo.localizacionsensor ADD CONSTRAINT cns_ubicacion_1 CHECK ( statusid = ANY (ARRAY[0, 1]) );

CREATE INDEX idx_localizacionsensor ON thermo.localizacionsensor  ( localizacionid );

CREATE INDEX idx_localizacionsensor_0 ON thermo.localizacionsensor  ( sensorid );

CREATE  TABLE thermo.medicion ( 
	medicionid           bigint  NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	localizacionsensorid integer  NOT NULL  ,
	valor                double precision  NOT NULL  ,
	fecha                timestamptz  NOT NULL  ,
	usercreatedid        integer  NOT NULL  ,
	datecreated          timestamptz DEFAULT now() NOT NULL  ,
	CONSTRAINT pk_medicion PRIMARY KEY ( medicionid )
 );

CREATE INDEX brin_medicion_fecha ON thermo.medicion  ( fecha );

CREATE UNIQUE INDEX unq_medicion_sensor_metrica_fecha ON thermo.medicion ( localizacionsensorid, fecha );

CREATE  TABLE thermo.umbral ( 
	umbralid             bigint  NOT NULL GENERATED  BY DEFAULT AS IDENTITY ,
	localizacionsensorid integer  NOT NULL  ,
	criticidadid         integer  NOT NULL  ,
	umbral               varchar(50)  NOT NULL  ,
	maximo               double precision  NOT NULL  ,
	minimo               double precision  NOT NULL  ,
	estandar             double precision    ,
	statusid             integer DEFAULT 1 NOT NULL  ,
	usercreatedid        integer  NOT NULL  ,
	datecreated          timestamptz DEFAULT now() NOT NULL  ,
	usermodifiedid       integer  NOT NULL  ,
	datemodified         timestamptz DEFAULT now() NOT NULL  ,
	CONSTRAINT pk_umbral PRIMARY KEY ( umbralid )
 );

ALTER TABLE thermo.umbral ADD CONSTRAINT cns_umbral CHECK ( statusid = ANY (ARRAY[0, 1]) );

CREATE  TABLE thermo.alerta ( 
	uuid_alerta          uuid DEFAULT gen_random_uuid() NOT NULL  ,
	usercreatedid        integer  NOT NULL  ,
	medicionid           bigint  NOT NULL  ,
	umbralid             bigint  NOT NULL  ,
	fecha                timestamptz DEFAULT now() NOT NULL  ,
	statusid             integer DEFAULT 1 NOT NULL  ,
	datecreated          timestamptz DEFAULT now() NOT NULL  ,
	CONSTRAINT unq_alerta UNIQUE ( umbralid, medicionid, fecha ) ,
	CONSTRAINT alerta_uuid_alerta_key UNIQUE ( uuid_alerta ) 
 );

ALTER TABLE thermo.alerta ADD CONSTRAINT cns_alerta_statusid CHECK ( statusid = ANY (ARRAY[0, 1]) );

CREATE INDEX idx_alerta_umbralid ON thermo.alerta  ( umbralid );

CREATE INDEX idx_alerta ON thermo.alerta  ( medicionid, fecha );

CREATE  TABLE thermo.audit_log_umbral ( 
	auditid              bigint  NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	umbralid             bigint  NOT NULL  ,
	old_minimo           double precision    ,
	new_minimo           double precision    ,
	old_maximo           double precision    ,
	new_maximo           double precision    ,
	old_criticidadid     integer    ,
	new_criticidadid     integer    ,
	accion               varchar(10)  NOT NULL  ,
	modified_by          integer  NOT NULL  ,
	modified_at          timestamptz DEFAULT now() NOT NULL  ,
	CONSTRAINT audit_log_umbral_pkey PRIMARY KEY ( auditid )
 );

ALTER TABLE thermo.audit_log_umbral ADD CONSTRAINT audit_log_umbral_accion_check CHECK ( accion)::text = ANY ((ARRAY['INSERT'::character varying, 'UPDATE'::character varying, 'DELETE'::character varying])::text[] );

CREATE  TABLE thermo.perfilumbral ( 
	perfilid             integer  NOT NULL  ,
	umbralid             bigint  NOT NULL  ,
	statusid             integer DEFAULT 1 NOT NULL  ,
	usercreatedid        integer  NOT NULL  ,
	datecreated          timestamptz DEFAULT now() NOT NULL  ,
	usermodifiedid       integer  NOT NULL  ,
	datemodified         timestamptz DEFAULT now() NOT NULL  ,
	CONSTRAINT pk_perfilumbral PRIMARY KEY ( perfilid, umbralid )
 );

ALTER TABLE thermo.perfilumbral ADD CONSTRAINT cns_perfilumbral CHECK ( statusid = ANY (ARRAY[0, 1]) );

CREATE INDEX idx_perfilumbral_umbral_act ON thermo.perfilumbral  ( umbralid, perfilid ) WHERE (statusid = 1);

CREATE INDEX idx_perfilumbral_perfil_act ON thermo.perfilumbral  ( perfilid ) WHERE (statusid = 1);

CREATE INDEX idx_perfilumbral_lookup_robusto ON thermo.perfilumbral  ( umbralid, perfilid, statusid ) WHERE (statusid = 1);

ALTER TABLE thermo.alerta ADD CONSTRAINT fk_alerta_medicion FOREIGN KEY ( medicionid ) REFERENCES thermo.medicion( medicionid );

ALTER TABLE thermo.alerta ADD CONSTRAINT fk_alerta_umbral FOREIGN KEY ( umbralid ) REFERENCES thermo.umbral( umbralid );

ALTER TABLE thermo.audit_log_umbral ADD CONSTRAINT fk_audit_log_umbral_umbral FOREIGN KEY ( umbralid ) REFERENCES thermo.umbral( umbralid );

ALTER TABLE thermo.contacto ADD CONSTRAINT fk_contacto_usuario FOREIGN KEY ( usuarioid ) REFERENCES thermo.usuario( usuarioid );

ALTER TABLE thermo.contacto ADD CONSTRAINT fk_contacto_codigotelefono FOREIGN KEY ( codigotelefonoid ) REFERENCES thermo.codigotelefono( codigotelefonoid );

ALTER TABLE thermo.correo ADD CONSTRAINT fk_correo_usuario FOREIGN KEY ( usuarioid ) REFERENCES thermo.usuario( usuarioid );

ALTER TABLE thermo.empresa ADD CONSTRAINT fk_empresa_pais FOREIGN KEY ( paisid ) REFERENCES thermo.pais( paisid );

ALTER TABLE thermo.fundo ADD CONSTRAINT fk_fundo_empresa FOREIGN KEY ( empresaid ) REFERENCES thermo.empresa( empresaid );

ALTER TABLE thermo.localizacion ADD CONSTRAINT fk_localizacion_ubicacion FOREIGN KEY ( ubicacionid ) REFERENCES thermo.ubicacion( ubicacionid );

ALTER TABLE thermo.localizacion ADD CONSTRAINT fk_localizacion_entidad FOREIGN KEY ( entidadid ) REFERENCES thermo.entidad( entidadid );

ALTER TABLE thermo.localizacionsensor ADD CONSTRAINT fk_localizacionsensor_localizacion FOREIGN KEY ( localizacionid ) REFERENCES thermo.localizacion( localizacionid );

ALTER TABLE thermo.localizacionsensor ADD CONSTRAINT fk_localizacionsensor_metricasensor FOREIGN KEY ( sensorid, metricaid ) REFERENCES thermo.metricasensor( sensorid, metricaid );

ALTER TABLE thermo.medicion ADD CONSTRAINT fk_medicion_localizacionsensor FOREIGN KEY ( localizacionsensorid ) REFERENCES thermo.localizacionsensor( localizacionsensorid );

ALTER TABLE thermo.mensaje ADD CONSTRAINT fk_mensaje_contacto FOREIGN KEY ( contactoid ) REFERENCES thermo.contacto( contactoid );

ALTER TABLE thermo.metricasensor ADD CONSTRAINT fk_metricasensor_metrica FOREIGN KEY ( metricaid ) REFERENCES thermo.metrica( metricaid );

ALTER TABLE thermo.metricasensor ADD CONSTRAINT fk_metricasensor_sensor FOREIGN KEY ( sensorid ) REFERENCES thermo.sensor( sensorid );

ALTER TABLE thermo.perfil ADD CONSTRAINT fk_perfil_perfil FOREIGN KEY ( jefeid ) REFERENCES thermo.perfil( perfilid );

ALTER TABLE thermo.perfilumbral ADD CONSTRAINT fk_perfilumbral_perfil FOREIGN KEY ( perfilid ) REFERENCES thermo.perfil( perfilid );

ALTER TABLE thermo.perfilumbral ADD CONSTRAINT fk_perfilumbral_umbral FOREIGN KEY ( umbralid ) REFERENCES thermo.umbral( umbralid );

ALTER TABLE thermo.sensor ADD CONSTRAINT fk_sensor_tipo FOREIGN KEY ( tipoid ) REFERENCES thermo.tipo( tipoid );

ALTER TABLE thermo.ubicacion ADD CONSTRAINT fk_ubicacion_fundo FOREIGN KEY ( fundoid ) REFERENCES thermo.fundo( fundoid );

ALTER TABLE thermo.umbral ADD CONSTRAINT fk_umbral_criticidad FOREIGN KEY ( criticidadid ) REFERENCES thermo.criticidad( criticidadid );

ALTER TABLE thermo.umbral ADD CONSTRAINT fk_umbral_localizacionsensor FOREIGN KEY ( localizacionsensorid ) REFERENCES thermo.localizacionsensor( localizacionsensorid );

ALTER TABLE thermo.usuarioperfil ADD CONSTRAINT fk_usuarioperfil_usuario FOREIGN KEY ( usuarioid ) REFERENCES thermo.usuario( usuarioid );

ALTER TABLE thermo.usuarioperfil ADD CONSTRAINT fk_usuarioperfil_perfil FOREIGN KEY ( perfilid ) REFERENCES thermo.perfil( perfilid );

CREATE OR REPLACE VIEW thermo.v_ingestion_resumen AS SELECT count(*) FILTER (WHERE (sensor_valor.statusid = 1)) AS registros_procesados,
    count(*) FILTER (WHERE (sensor_valor.statusid = '-1'::integer)) AS pendientes,
    count(*) FILTER (WHERE (sensor_valor.statusid < 0)) AS errores,
    date_trunc('hour'::text, sensor_valor.fecha) AS hora
   FROM thermo.sensor_valor
  GROUP BY (date_trunc('hour'::text, sensor_valor.fecha))
  ORDER BY (date_trunc('hour'::text, sensor_valor.fecha)) DESC;

CREATE OR REPLACE VIEW thermo.v_mensaje_detalle_ext AS SELECT m.uuid_origen,
    m.tipo_origen,
    m.contactoid,
    m.mensaje,
    m.fecha AS fecha_mensaje,
    m.statusid AS status_mensaje,
    m.usercreatedid,
    m.datecreated AS fecha_creacion_mensaje,
    COALESCE(a.umbralid, ac.umbralid) AS umbralid,
    a.uuid_alerta,
    ac.uuid_alertaconsolidado,
    COALESCE(a.fecha, ac.fechaultimo) AS fecha_evento,
    COALESCE(a.statusid, ac.statusid) AS status_origen,
        CASE
            WHEN ((m.tipo_origen)::text = 'alerta'::text) THEN 'Alerta individual'::text
            WHEN ((m.tipo_origen)::text = 'alertaconsolidado'::text) THEN 'Alerta consolidada'::text
            ELSE NULL::text
        END AS descripcion_tipo,
    c.usuarioid,
    u.login AS usuario_login,
    u.firstname AS usuario_nombre,
    u.lastname AS usuario_apellido,
    co.correo AS correo_usuario,
    c.celular,
    ct.codigotelefono AS codigo_telefono,
    ct.paistelefono AS pais_telefono,
    c.datecreated AS fecha_registro_contacto,
    c.statusid AS status_contacto
   FROM ((((((thermo.mensaje m
     LEFT JOIN thermo.alerta a ON ((((m.tipo_origen)::text = 'alerta'::text) AND (a.uuid_alerta = m.uuid_origen))))
     LEFT JOIN thermo.alertaconsolidado ac ON ((((m.tipo_origen)::text = 'alertaconsolidado'::text) AND (ac.uuid_alertaconsolidado = m.uuid_origen))))
     LEFT JOIN thermo.contacto c ON ((m.contactoid = c.contactoid)))
     LEFT JOIN thermo.usuario u ON ((c.usuarioid = u.usuarioid)))
     LEFT JOIN thermo.correo co ON (((co.usuarioid = u.usuarioid) AND (co.statusid = 1))))
     LEFT JOIN thermo.codigotelefono ct ON (((ct.codigotelefonoid = c.codigotelefonoid) AND (ct.statusid = 1))));

CREATE TRIGGER trg_auditar_umbral AFTER INSERT OR UPDATE ON thermo.umbral FOR EACH ROW EXECUTE FUNCTION thermo.fn_auditar_umbral();

CREATE TRIGGER trg_sensor_valor_to_medicion AFTER INSERT ON thermo.sensor_valor FOR EACH ROW EXECUTE FUNCTION thermo.fn_sensor_valor_to_medicion();

CREATE TRIGGER trg_validar_mensaje_origen BEFORE INSERT ON thermo.mensaje FOR EACH ROW EXECUTE FUNCTION thermo.fn_validar_mensaje_origen();

CREATE TRIGGER trg_validar_umbral BEFORE INSERT OR UPDATE ON thermo.umbral FOR EACH ROW EXECUTE FUNCTION thermo.fn_validar_umbral_minimo_maximo();

CREATE OR REPLACE FUNCTION thermo.fn_auditar_umbral()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'thermo', 'auth', 'public'
AS $function$BEGIN
  IF TG_OP = 'INSERT' THEN
    INSERT INTO thermo.audit_log_umbral(umbralid,new_minimo,new_maximo,new_criticidadid,modified_by,accion)
    VALUES (NEW.umbralid, NEW.minimo, NEW.maximo, NEW.criticidadid, NEW.usermodifiedid, 'INSERT');
  ELSIF TG_OP = 'UPDATE' THEN
    INSERT INTO thermo.audit_log_umbral(umbralid,old_minimo,new_minimo,old_maximo,new_maximo,old_criticidadid,new_criticidadid,modified_by,accion)
    VALUES (NEW.umbralid, OLD.minimo, NEW.minimo, OLD.maximo, NEW.maximo, OLD.criticidadid, NEW.criticidadid, NEW.usermodifiedid, 'UPDATE');
  END IF;
  RETURN NULL;
END;$function$
;

CREATE OR REPLACE FUNCTION thermo.fn_sensor_valor_to_medicion()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'thermo', 'auth', 'public'
AS $function$
DECLARE
  v_sensorid integer;
  v_user integer := 0;
  v_exists boolean;
BEGIN
  -------------------------------------------------------------------
  -- Paso 1: Resolver sensorid desde la localizacionsensorid
  -------------------------------------------------------------------
  SELECT ls.sensorid
    INTO v_sensorid
  FROM thermo.localizacionsensor ls
  WHERE ls.localizacionsensorid = NEW.id_sensorlocalizacion;
  IF v_sensorid IS NULL THEN
    -- 🚫 Localización no válida → error lógico
    INSERT INTO thermo.sensor_valor_error(error, id_fundo, id_sensorlocalizacion, id_metrica, valor, fecha, statusid)
    VALUES ('localizacionsensor inexistente', NEW.id_fundo, NEW.id_sensorlocalizacion, NEW.id_metrica, NEW.valor, NEW.fecha, -1);
    RETURN NULL;
  END IF;
  -------------------------------------------------------------------
  -- Paso 2: Validar relación métrica ↔ sensor usando EXISTS
  -------------------------------------------------------------------
  SELECT EXISTS (
    SELECT 1 FROM thermo.metricasensor
     WHERE sensorid = v_sensorid
       AND metricaid = NEW.id_metrica
  ) INTO v_exists;
  IF NOT v_exists THEN
    -- 🚫 Métrica no aplicable al sensor → error lógico
    INSERT INTO thermo.sensor_valor_error(error, id_fundo, id_sensorlocalizacion, id_metrica, valor, fecha, statusid)
    VALUES ('métrica no válida para este sensor', NEW.id_fundo, NEW.id_sensorlocalizacion, NEW.id_metrica, NEW.valor, NEW.fecha, -1);
    RETURN NULL;
  END IF;
  -------------------------------------------------------------------
  -- Paso 3: Insertar medición solo si no existe (ON CONFLICT DO NOTHING)
  -------------------------------------------------------------------
  BEGIN
    INSERT INTO thermo.medicion(localizacionsensorid, sensorid, metricaid, fecha, valor, usercreatedid)
    VALUES (NEW.id_sensorlocalizacion, v_sensorid, NEW.id_metrica, NEW.fecha, NEW.valor, v_user)
    ON CONFLICT DO NOTHING;  -- evita violaciones UNIQUE sin generar error
    -----------------------------------------------------------------
    -- Paso 4: Actualizar estado en sensor_valor a procesado (solo si insertó)
    -----------------------------------------------------------------
    IF FOUND THEN
      UPDATE thermo.sensor_valor
         SET statusid = 1
       WHERE id_fundo = NEW.id_fundo
         AND id_sensorlocalizacion = NEW.id_sensorlocalizacion
         AND id_metrica = NEW.id_metrica
         AND fecha = NEW.fecha;
    END IF;
  EXCEPTION
    WHEN OTHERS THEN
      -- ⚠️ Registrar error solo en casos reales de fallo de BD (no duplicados)
      INSERT INTO thermo.sensor_valor_error(error, id_fundo, id_sensorlocalizacion, id_metrica, valor, fecha, statusid)
      VALUES (format('Error inesperado: %s', SQLERRM),
              NEW.id_fundo, NEW.id_sensorlocalizacion, NEW.id_metrica, NEW.valor, NEW.fecha, -1);
  END;
  RETURN NULL; -- no bloquear el insert original
END;
$function$
;

CREATE OR REPLACE FUNCTION thermo.fn_validar_mensaje_origen()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'thermo', 'public'
AS $function$DECLARE
  v_existe boolean;
  v_log_only boolean := true; -- ⚙️ Cambia a true si quieres registrar errores sin bloquear el insert
BEGIN
  -- 🔸 Validar tipo de origen permitido
  IF NEW.tipo_origen NOT IN ('alerta', 'alertaconsolidado') THEN
    IF v_log_only THEN
      INSERT INTO thermo.mensaje_error (uuid_origen, tipo_origen, detalle, usercreatedid)
      VALUES (NEW.uuid_origen, NEW.tipo_origen, 'Tipo de origen inválido', NEW.usercreatedid);
      RETURN NULL;  -- evita el insert real
    ELSE
      RAISE EXCEPTION 'Tipo de origen inválido: %', NEW.tipo_origen;
    END IF;
  END IF;
  -- 🔸 Validar existencia eficiente según tipo_origen
  IF NEW.tipo_origen = 'alerta' THEN
    SELECT EXISTS (
      SELECT 1 FROM thermo.alerta WHERE uuid_alerta = NEW.uuid_origen
    ) INTO v_existe;
  ELSE
    SELECT EXISTS (
      SELECT 1 FROM thermo.alertaconsolidado WHERE uuid_alertaconsolidado = NEW.uuid_origen
    ) INTO v_existe;
  END IF;
  -- 🔸 Si no existe, registrar o abortar
  IF NOT v_existe THEN
    IF v_log_only THEN
      INSERT INTO thermo.mensaje_error (uuid_origen, tipo_origen, detalle, usercreatedid)
      VALUES (NEW.uuid_origen, NEW.tipo_origen, 'UUID no encontrado en tabla de origen', NEW.usercreatedid);
      RETURN NULL;  -- ignora el insert original
    ELSE
      RAISE EXCEPTION 'UUID % no encontrado en la tabla de origen %', NEW.uuid_origen, NEW.tipo_origen;
    END IF;
  END IF;
  RETURN NEW;  -- pasa la validación
END;$function$
;

CREATE OR REPLACE FUNCTION thermo.fn_validar_umbral_minimo_maximo() 
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'thermo', 'auth', 'public'
AS $function$
BEGIN
    IF NEW.minimo >= NEW.maximo THEN
        RAISE EXCEPTION 'El valor mínimo (%s) debe ser menor que el valor máximo (%s)', NEW.minimo, NEW.maximo;
    END IF;
    RETURN NEW;
END;
$function$
;

